name: aoc22-haskell
version: 0.1.0.0
github: "githubuser/aoc22-haskell"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/aoc22-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - MissingH
  - unordered-containers
  - ghc
  - regex-pcre
  - extra
  - containers
  - mtl

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs:
    - src
    - src/day1
    - src/day2
    - src/day3
    - src/day4
    - src/day5
    - src/day6
    - src/day7
    - src/day8
    - src/day9

executables:
  aoc22-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc22-haskell

tests:
  aoc22-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc22-haskell
